'use strict'

module.exports = {
	CARDINAL_POINTS_REGEX: /([N||W||E||S])/,
	AVAILABLE_ORDERS_REGEX: /([FLR])*/,
	DIRECTION2ANGLE_MAP: {
		"E": 0,
		"N": 90,
		"W": 180,
		"S": 270
	},
	LOST_ROBOT_STATUS: 'LOST',
	ACTIVE_ROBOT_STATUS: 'ACTIVE',
	CREATED_ROBOT_STATUS: 'CREATED'
}